version: '3'
services:
  packages-service:
    container_name: packages-service
    build: .
    working_dir: /usr/src/app
    # command: shotgun --help
    command: shotgun server.rb -o 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "4567:4567"
      - "9393:9393"
    # depends_on:
    #   - packages-db
    environment:
      DEBUG: 1
    # external_links:
      # - redis-session
      # - packages-db
    network_mode: bridge

  # packages-db:
  #   container_name: packages-db
  #   image: mysql:5.7
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: passwordroot
  #     MYSQL_USER: packages
  #     MYSQL_PASSWORD: password123
  #     MYSQL_DATABASE: packages
  #   network_mode: bridge
